version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      .env
    container_name: petgram-app
    volumes: 
      - ".:/app"
    ports:
      - "8081:8080"